// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/commerce/manage-bombink/user/create": {
            "post": {
                "description": "Service to activate missions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ActivateUser"
                ],
                "summary": "Service to activate missions",
                "parameters": [
                    {
                        "description": "Save user",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.BombinkResponse"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "user guardado con éxito",
                        "schema": {
                            "$ref": "#/definitions/dtos.BombinkResponse"
                        }
                    },
                    "500": {
                        "description": "Cuando ocurre un error inexperado",
                        "schema": {
                            "$ref": "#/definitions/api.RetomaRegistroResponseErrorInexperado"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Data": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "IDMissionNoValid"
                }
            }
        },
        "api.RetomaRegistroResponseErrorInexperado": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.Data"
                },
                "message": {
                    "type": "string",
                    "example": "Ocurrio un error inexperado"
                }
            }
        },
        "dtos.BombinkResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1323",
	BasePath:         "/commerce/manage-bombink",
	Schemes:          []string{"http"},
	Title:            "Bombink End Points",
	Description:      "Service to connect challenges",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
